#!/data/data/com.termux/files/usr/bin/bash

clear
kill_color=$'\e[0m'
command -v youtube-dl &>/dev/null || printf "\e[031m Please install Youtube-dl manualy or run the the install.sh script again.\n$kill_color"

#uncomment me if you wish :)
#[[ -f ~/bin ]] || printf "\e[031m Please Run the the install.sh script.\n$kill_color"



echo -e "\e[036m" "═════════════[• NASHAT SCRIPT •]═════════════"
echo -e "\e[031m"  " Project Name  : TERMUX VIDEO"
echo -e "\e[031m"  " Telegram      :https://t.me/TRON_SYRIA"
echo -e "\e[031m"  " CREATOR       :TRON OF SYRIA [NASHAT]"                                                                
echo -e "\e[036m" "═════════════[• NASHAT SCRIPT •]═════════════\n"
echo -e "\e[035m" "   [𝗦𝗲𝗹𝗲𝗰𝘁 𝗔 𝗙𝗼𝗿𝗺𝗮𝘁]"
echo -e "\n"
echo -e "\e[031m" "   1. Music Mp3\n\n"
echo -e "\e[031m" "   2. Video 360p\n\n"
echo -e "\e[031m" "   3. Video 480p\n\n"
echo -e "\e[031m" "   4. Video 720p\n\n"
echo -e "\e[031m" "   5. Video 1080p\n\n"
echo -e "\e[031m" "   6. Video 2160p\n\n"
echo -e "\e[031m" "   7. Exit   TERMUX VIDEO\n\n" # Added
command='-no-mtime -o /data/data/com.termux/files/home/storage/shared/Youtube/%(title)s.%(ext)s -f'

#Edit From Oak Atsume 
printf "\e[036m ╚═:➤  $kill_color"
read option

if [[ -z $option ]];
then
	clear
	printf "\e[031m Please choose a option!\n$kill_color"
else
case $option in #Make Case list
	1)
	echo "$command 140" > ~/.config/youtube-dl/config #option 1
	youtube-dl $1
	;;
	2)
	echo "$command \"best[height<=360]\"" > ~/.config/youtube-dl/config #option 2
	youtube-dl $1
	;;
	3)
	echo "$command \"best[height<=480]\"" > ~/.config/youtube-dl/config #option 3
	youtube-dl $1
	;;
	4)
	echo "$command \"best[height<=720]\"" > ~/.config/youtube-dl/config #option 4
	youtube-dl $1
	;;
	5)
	echo "$command \"best[height<=1080]\"" > ~/.config/youtube-dl/config #option 5
	youtube-dl $1
	;;
	6)
	echo "$command \"best[height<=2160]\"" > ~/.config/youtube-dl/config
    	youtube-dl $1
	;;
	7)
	break
	;;
esac 
fi


#There's a cat on the code!!
#🚬🎲


#TRON OF SYRIA 
#SYRIA#
#😂#
#🇸🇾#
